#!/bin/bash

set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE USER test WITH PASSWORD 'postgres';
	CREATE DATABASE test;
	ALTER DATABASE test OWNER TO test
EOSQL

echo "FINISHED ADDING USER AND GRANTING PRIVILAGES"